/* -------------- BACK-END (API, database, servicio) -------------- */
const databaseItems = [
  {
    id: 1,
    title: "Burn Notice: The Fall of Sam Axe",
    category: "Crime|Drama|Mystery",
    stock: 1,
    imgurl:
      "https://images-na.ssl-images-amazon.com/images/S/pv-target-images/2596301d69a4d0ce86a41d4ef6fdb5e19eabe66ac45cab63eeb97dc45d840254._RI_V_TTW_.jpg",
    price: 3748.37,
    detail: 2007,
  },
  {
    id: 2,
    title: "Bloody Murder 2: Closing Camp",
    category: "Drama|Horror|Mystery|Thriller",
    stock: 4,
    imgurl: "http://dummyimage.com/x.png/cc0000/ffffff",
    price: 509.21,
    detail: 2005,
  },
  {
    id: 3,
    title: "White Palms (Fehér tenyér)",
    category: "Drama",
    stock: 2,
    imgurl: "http://dummyimage.com/x.png/cc0000/ffffff",
    price: 859.69,
    detail: 1985,
  },
  {
    id: 4,
    title: "Rocky",
    category: "Drama",
    stock: 4,
    imgurl:
      "https://images-na.ssl-images-amazon.com/images/S/pv-target-images/2596301d69a4d0ce86a41d4ef6fdb5e19eabe66ac45cab63eeb97dc45d840254._RI_V_TTW_.jpg",
    price: 1368.86,
    detail: 2007,
  },
  {
    id: 5,
    title: "Sasha (Sascha)",
    category: "Comedy|Drama",
    stock: 8,
    imgurl: "http://dummyimage.com/x.png/ff4444/ffffff",
    price: 3654.42,
    detail: 1989,
  },
  {
    id: 6,
    title: "Tae Guk Gi: The Brotherhood of War (Taegukgi hwinalrimyeo)",
    category: "Action|Drama|War",
    stock: 10,
    imgurl: "http://dummyimage.com/x.png/cc0000/ffffff",
    price: 2678.68,
    detail: 2009,
  },
  {
    id: 7,
    title: "Hot Rock, The",
    category: "Comedy|Crime",
    stock: 5,
    imgurl: "http://dummyimage.com/x.png/ff4444/ffffff",
    price: 1360.19,
    detail: 2007,
  },
  {
    id: 8,
    title: "Jolene",
    category: "Drama",
    stock: 10,
    imgurl: "http://dummyimage.com/x.png/5fa2dd/ffffff",
    price: 4273.56,
    detail: 2003,
  },
  {
    id: 9,
    title: "Twelve Angry Men",
    category: "Drama",
    stock: 1,
    imgurl: "http://dummyimage.com/x.png/ff4444/ffffff",
    price: 2176.61,
    detail: 1993,
  },
  {
    id: 10,
    title: "Agatha",
    category: "Drama|Mystery",
    stock: 6,
    imgurl: "http://dummyimage.com/x.png/5fa2dd/ffffff",
    price: 1357.91,
    detail: 2007,
  },
  {
    id: 11,
    title: "Mike Birbiglia: What I Should Have Said Was Nothing",
    category: "Comedy",
    stock: 4,
    imgurl: "http://dummyimage.com/x.png/5fa2dd/ffffff",
    price: 1629.0,
    detail: 1987,
  },
  {
    id: 12,
    title: "Broken Trail",
    category: "Action|Adventure|Crime|Drama|Western",
    stock: 7,
    imgurl: "http://dummyimage.com/x.png/cc0000/ffffff",
    price: 2168.13,
    detail: 2003,
  },
  {
    id: 13,
    title: "Batman: Year One",
    category: "Action|Animation|Crime",
    stock: 1,
    imgurl: "http://dummyimage.com/x.png/cc0000/ffffff",
    price: 2343.94,
    detail: 1999,
  },
  {
    id: 14,
    title: "Cowboy Bebop: The Movie (Cowboy Bebop: Tengoku no Tobira)",
    category: "Action|Animation|Sci-Fi|Thriller",
    stock: 6,
    imgurl: "http://dummyimage.com/x.png/ff4444/ffffff",
    price: 2070.58,
    detail: 1999,
  },
  {
    id: 15,
    title: "Loves of a Blonde (Lásky jedné plavovlásky)",
    category: "Comedy|Drama|Romance",
    stock: 4,
    imgurl: "http://dummyimage.com/x.png/5fa2dd/ffffff",
    price: 1903.27,
    detail: 2008,
  },
  {
    id: 16,
    title: "Lessons of Darkness (Lektionen in Finsternis)",
    category: "Documentary|War",
    stock: 10,
    imgurl: "http://dummyimage.com/x.png/dddddd/000000",
    price: 408.63,
    detail: 1991,
  },
  {
    id: 17,
    title: "Going in Style",
    category: "Comedy|Drama",
    stock: 7,
    imgurl: "http://dummyimage.com/x.png/cc0000/ffffff",
    price: 4562.86,
    detail: 1988,
  },
  {
    id: 18,
    title: "Three Musketeers, The",
    category: "Action|Adventure|Comedy|Romance",
    stock: 3,
    imgurl: "http://dummyimage.com/x.png/cc0000/ffffff",
    price: 1243.73,
    detail: 2006,
  },
  {
    id: 19,
    title: "Guru, The",
    category: "Comedy|Romance",
    stock: 3,
    imgurl: "http://dummyimage.com/x.png/5fa2dd/ffffff",
    price: 2956.54,
    detail: 1997,
  },
  {
    id: 20,
    title: "Alexandra's Project",
    category: "Drama|Thriller",
    stock: 9,
    imgurl: "http://dummyimage.com/x.png/5fa2dd/ffffff",
    price: 2400.9,
    detail: 2006,
  },
];

function getItems() {
  return new Promise((resolve) => {
    setTimeout(() => {
      resolve(databaseItems);
    }, 2000);
  });
}

export default getItems;
